# Generated by Django 3.1.4 on 2021-01-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210116_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
