# Generated by Django 3.1.4 on 2021-01-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210117_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
