# Generated by Django 3.1.4 on 2021-01-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210121_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_variants',
            new_name='productVariants',
        ),
    ]
