# Generated by Django 3.1.4 on 2021-01-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
