# Generated by Django 3.1.4 on 2021-01-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
